const String NOTIFICATION_ALL_NEARBY = "NOTIFICATION_ALL_NEARBY";
const String NOTIFICATION_FAVOURITE_ONLY = "NOTIFICATION_FAVOURITE_ONLY";
const String NOTIFICATION_OFF = "NOTIFICATION_OFF";

const String NOTIFICATION_ALL_NEARBY_OPTION = "All Nearby Clubs";
const String NOTIFICATION_FAVOURITE_ONLY_OPTION = "Only Favourite Clubs";
const String NOTIFICATION_OFF_OPTION = "Off";

const String CHAT_NOTIFICATION_ON = "CHAT_NOTIFICATION_ON";
const String CHAT_NOTIFICATION_OFF = "CHAT_NOTIFICATION_OFF";

const String CHAT_NOTIFICATION_ON_OPTION = "On";
const String CHAT_NOTIFICATION_OFF_OPTION = "Off";
